from transformers import pipeline

text = """
Hello guys welcome to our channel 3 minutes master where you can learn any concept in 3 minutes. In this video I want to give you a basic idea regarding introduction to Java. Let's start. As we all know Java is a popular programming language. You know it is developed in the year 1995 and Java previously is owned by some micro systems now owned by another chain called R-throw. You don't believe the 3 billion devices in the world are run by Java. Now let's focus on which Java is used in real time. So and the first one is we are well ever about this particular term called apps so-called mobile applications are developed using this particular Java platform especially for developing Android applications. Next, desktop applications and that are used in our personal computers or also office computers as well. And next one is web applications. Now most of the devices use internet by this we run certain applications over web called web applications and the next one is very interesting one games. This is the area where Java have done wonders worldwide and certainly a big sensation. Most of the games are developed using this particular platform and the last one is web server. And a web server is a server software that satisfies the client request worldwide done by the Java and many more. And next why to use this particular Java? You know what? Java works on different platforms such as Windows, even on Mac, on open sources like Linux and different operating systems like Raspberry Pi and many more systems. And next, the main thing why Java is popular is it is of free we call it as open source. It has an important feature like security and it is very fast and it is robust we call it as powerful and it has huge support as millions of developers work on it. Finally, Java is easy and simple to use just give it fine.
"""

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
summary = summarizer(text, max_length=100, min_length=30, do_sample=False)[0]["summary_text"]
print("Summary:", summary)
